// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtRO6lIWQbEBIM7j9G5AE2YcflspW7yXc',
    appId: '1:116782521214:android:98e388a0cd2436e9aeb12f',
    messagingSenderId: '116782521214',
    projectId: 'masaratalnur',
    storageBucket: 'masaratalnur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX0eR6S7fbv22XXzac6DlipoTwKKGXTvQ',
    appId: '1:116782521214:ios:883734495ae7032aaeb12f',
    messagingSenderId: '116782521214',
    projectId: 'masaratalnur',
    storageBucket: 'masaratalnur.firebasestorage.app',
    androidClientId: '116782521214-084rkai81rvmk2mcrf2il05862o8gfk8.apps.googleusercontent.com',
    iosClientId: '116782521214-jhi8lrokp67pc38bj7lbijuu4nv3f44i.apps.googleusercontent.com',
    iosBundleId: 'com.oussama.masaratAlnur',
  );

}